### ISSUE TITLE
Update secp256r1 Package to utilize `agent_dart 1.0.0-dev.18`

### ISSUE THREAD

**Issue by Ariflo** [AstroxNetwork/flutter_secp256r1#7]
Our package is currently running into this issue: https://github.com/magiclabs/magic-flutter/issues/45 due to an error with legacy version of `agent_dart 1.0.0-dev.17`. Could you please consider releasing a new version of this package that points to the latest version of `agent_dart`?  Thanks!

**Comment by Ariflo** [comment]
For reference, here's the original issue on agent_dart's repo: https://github.com/AstroxNetwork/agent_dart/issues/70

**Comment by AlexV525** [comment]
This can be done by `flutter pub upgrade` automatically without any changes to downstream packages.
